### ISSUE TITLE
No Gantt Chart button added

### ISSUE THREAD

**Issue by lslaz1** [it-projects-llc/addons-dev#176]
None of the resources are being loaded

I installed web_gantt8/project_gantt8. I can select start and end dates for the gantt view but there was no gantt button added for me to select.
On Odoo V9, chrome

<img width="216" alt="screen shot 2016-12-22 at 12 30 32 pm" src="https://cloud.githubusercontent.com/assets/10367837/21436099/777a4986-c842-11e6-9195-034e1c86354d.png">

^^^ same buttons after installed the modules.

Console error:
`Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://10.3.3.30:8069/web_gantt8/static/lib/dhtmlxGantt/codebase/dhtmlxgantt.css Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://10.3.3.30:8069/web_gantt8/static/lib/dhtmlxGantt/sources/dhtmlxcommon.js Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://10.3.3.30:8069/web_gantt8/static/lib/dhtmlxGantt/sources/dhtmlxgantt.js Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://10.3.3.30:8069/web_gantt8/static/src/js/gantt.js Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://10.3.3.30:8069/web_gantt8/static/src/css/gantt.css Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://10.3.3.30:8069/web_gantt8/static/lib/dhtmlxGantt/codebase/dhtmlxgantt.css Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://10.3.3.30:8069/web_gantt8/static/lib/dhtmlxGantt/sources/dhtmlxcommon.js Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://10.3.3.30:8069/web_gantt8/static/lib/dhtmlxGantt/sources/dhtmlxgantt.js Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://10.3.3.30:8069/web_gantt8/static/src/js/gantt.js Failed to load resource: the server responded with a status of 404 (NOT FOUND)
3view_manager.js:54 View type 'gantt8' is not present in the view registry.
(anonymous) @ view_manager.js:54
http://10.3.3.30:8069/web_gantt8/static/src/css/gantt.css Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://10.3.3.30:8069/web_gantt8/static/lib/dhtmlxGantt/codebase/dhtmlxgantt.css Failed to load resource: the server responded with a status of 404 (NOT FOUND)`

Firefox is a little better. There IS a button there but it doesn't work.

Console error:
```unreachable code after return statement[Learn More]  web.assets_backend.js:4350:356
View type 'gantt' is not present in the view registry.  web.assets_backend.js:3148:370
Error: QWeb2: Template 'GanttView' not found  web.assets_common.js:2444:7

**Comment by axatech01** [comment]
It happened to me, what I did was clear browser cache and uninstall a conficting app caled Website Page Admin and now it is working.

**Comment by lslaz1** [comment]
Excellent. Maybe that will help on my local machine. For some reason on production it works fine!
