### ISSUE TITLE
No Registration Form on Event Registration

### ISSUE THREAD

**Issue by stfl** [it-projects-llc/addons-dev#303]
Since #302 

When signed in and clicking on [Order now]. nothing happens..

```
2017-11-01 13:24:53,702 25464 INFO tg18_master_event_tests werkzeug: 127.0.0.1 - - [01/Nov/2017 13:24:53] "POST /event/tribal-gathering-2018-2018-02-23-2018-03-13-1/registration/new HTTP/1.0" 200 -
```

nothing else

**Comment by stfl** [comment]
I tested now on an old db where the popup seams to work.. (I don't know what's the difference... there..)

**Comment by stfl** [comment]
ok.. it seams to be caused by f0214bb4256e8182f62647319859e086406989ff
reverting it makes things work..

**Comment by yelizariev** [comment]
Is it depends on browser?

**Comment by yelizariev** [comment]
Fixed at https://github.com/it-projects-llc/addons-dev/pull/305
