### ISSUE TITLE
Test script for logout button + qr login

### ISSUE THREAD

**Issue by Railia** [it-projects-llc/addons-dev#358]
1.	Go to Settings-Users-Demo User
2.	Set Barcode, Set PIN
3.	Open POS session
4.	Click on left top of POS screen - Demo user (**Change Cashier** popup appears)
5.	Click on Exit
6.	Click on **Tap to unlock** (we check lock mode) (as result **Select User** dialog appears)
7.	Scan Demo user's barcode  (POS screen is unlocked)
8.	Repeat steps 4,5 (we check unlock mode)
9.	Scan Demo user's barcode (POS screen is unlocked)
10.	Repeat steps 4,5
11.	Click on **Tap to unlock** (**Select User** dialog appears)
12.  	Select Demo user
13.	Enter correct PIN (System opens)
14.	Enter incorrect PIN (**Password** dialog doesn’t disappear)
15.	Don’t enter PIN (**Password** dialog doesn’t disappear)

**Comment by yelizariev** [comment]
This issue will be moved to pos-addons repo

**Comment by ilmir-k** [comment]
The issue has been moved: 
https://github.com/it-projects-llc/pos-addons/issues/661
