### ISSUE TITLE
[pos_invoice_pay][Bug] Cash return creates credit for customer

### ISSUE THREAD

**Issue by janbec** [it-projects-llc/addons-dev#437]
## Steps to reproduce
Pay invoice or sale order via point of sale
pay with more money than expected, customer gets change

## Current Behavior
There is no account.move for the change leading to a erroneous credit for the customer
![image](https://user-images.githubusercontent.com/28890800/40271226-abffc37e-5b9a-11e8-8630-238f9e1225d3.png)

## Expected Behavior
If the payment is greater than the amount due, odoo should create the return account move like with a regular PoS sale. The change should not end up as a unreconciled credit.

I tested on my local VM, @ilmir-k could you have a look at it?

**Comment by ilmir-k** [comment]
@janbec 

Is that for 10th or 11th version?
I think you noticed that for 10.0 we added the field _**Difference Account**_ where you can put the change, i.e. to be able to use normal invoice payment flow like it's made via backend.

For 11.0 we have not added special account for that, but we can do it. Could this resolve your issue?

Please clarify why you need account move line like a return made with regular POS sale? Yes, we make payment of _regular invoices_ via POS, but actually it is not regular POS sale.

**Comment by janbec** [comment]
Sorry Ilmir, I found the necassary code block that was commented. So, it works just fine.

However, I wonder why that was the case. If you receive payment through the point of sale, the change is usually given back to the customer and should not add up to a credit. But anyhow, since it is working, you can close the issue - I forgot about the hardcoded modification...
