### ISSUE TITLE
[pos_sale_details] Feedback

### ISSUE THREAD

**Issue by janbec** [it-projects-llc/addons-dev#457]
## Total amount in returns
![image](https://user-images.githubusercontent.com/28890800/41335261-7c7a51c6-6ee8-11e8-8bb2-20a553f5f245.png)

The total amount is printed in net, should be gross (including taxes).

## Totals
Please create Total (column amount) row for the following sections:
- Returns
- Take money out and put money in 

## Sum of theoretical closing balance
![image](https://user-images.githubusercontent.com/28890800/41336337-3e303e04-6eec-11e8-9878-5f72ccf75a64.png)

If we compare theoretical closing balance to money counted, it should include the gross amount of:

- invoices and orders paid cash (not card)
- expenses
- Take Money out / put money in

`result['cash_register_balance_end'] = result['cash_register_balance_end']`
[Link to code](https://github.com/it-projects-llc/addons-dev/blob/6f3c2a5586b2c06971dc96e4d19b5b37e013664b/pos_sales_details_custom/report/sales_details_report.py#L85)

## Opening Balance
Please also print the opening_balance at the end before theoretical closing balance

## Sale Order / Invoices
Please also print the payment method after cashier.

## List of card transactions
Could you please append a list of all card transactions (payment != cash) at the end:

- Order Reference
- Datetime
- Payment methods (Credit Card, Debit card etc.)
- Cashier
- Amount

**Comment by ilmir-k** [comment]
@janbec 

> List of card transactions

Do you want us to add new section **List of card transactions** in report, right?

**Comment by janbec** [comment]
> >List of card transactions
> 
> Do you want us to add new section List of card transactions in report, right?

Yes, just like cash control and returns but please append at the very end.

**Comment by janbec** [comment]
## Number of payments computation
There are only 2 orders with payments in active session, but report will display all payments from pos:
![image](https://user-images.githubusercontent.com/28890800/41414759-35e2ee6c-6fe7-11e8-8fb5-0dfdb25816eb.png)
![image](https://user-images.githubusercontent.com/28890800/41415125-0df7590a-6fe8-11e8-81a1-d97480725bfb.png)

- The number of orders (right below date) is all orders
- I believe the number of payments is general all payments inlcuding take out/put in

Generally the filter for date doesn't seem to work as all entries across sessions are posted in report.
@ilmir-k can you take a look?

BTW: Good luck in the opening match tonight :)

**Comment by ilmir-k** [comment]
@janbec 

Ok, I'll check it

Thank you! Hope I will enjoy it and my team can pass their group at least :)
Good luck to Germany team too. They are really rock! :)

**Comment by ilmir-k** [comment]
@janbec 
We made the updates, so you can check it now by the runbot link above.

**Comment by janbec** [comment]
I think this happens when you print the report with an open session:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/mnt/odoo-extra/runbot/static/build/18043-pos-addons-11-0-pos-sales-detail-1d0b30/odoo/addons/web/controllers/main.py", line 1619, in report_download
    response = self.report_routes(reportname, converter='pdf', **dict(data))
  File "/mnt/odoo-extra/runbot/static/build/18043-pos-addons-11-0-pos-sales-detail-1d0b30/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/mnt/odoo-extra/runbot/static/build/18043-pos-addons-11-0-pos-sales-detail-1d0b30/odoo/addons/web/controllers/main.py", line 1564, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/mnt/odoo-extra/runbot/static/build/18043-pos-addons-11-0-pos-sales-detail-1d0b30/odoo/addons/base/ir/ir_actions_report.py", line 624, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/mnt/odoo-extra/runbot/static/build/18043-pos-addons-11-0-pos-sales-detail-1d0b30/odoo/addons/base/ir/ir_actions_report.py", line 654, in render_qweb_html
    data = report_model.get_report_values(docids, data=data)
  File "/mnt/odoo-extra/runbot/static/build/18043-pos-addons-11-0-pos-sales-detail-1d0b30/odoo/addons/point_of_sale/models/pos_order.py", line 1129, in get_report_values
    data.update(self.get_sale_details(data['date_start'], data['date_stop'], configs))
  File "/mnt/odoo-extra/runbot/static/build/18043-pos-addons-11-0-pos-sales-detail-1d0b30/odoo/addons/pos_sales_details_custom/report/sales_details_report.py", line 47, in get_sale_details
    'pay_num': sum([p['pay_num'] for p in result['payments']] + [0]),
  File "/mnt/odoo-extra/runbot/static/build/18043-pos-addons-11-0-pos-sales-detail-1d0b30/odoo/addons/pos_sales_details_custom/report/sales_details_report.py", line 47, in <listcomp>
    'pay_num': sum([p['pay_num'] for p in result['payments']] + [0]),
KeyError: 'pay_num'
```

![image](https://user-images.githubusercontent.com/28890800/42042893-6e059a74-7af5-11e8-9c18-345946519339.png)
The marked column shows the amount of coins bills at opening. Either we need a column with the amount at closing or drop the column if there is not one for closing.

![image](https://user-images.githubusercontent.com/28890800/42043206-2b56b57c-7af6-11e8-9016-f421e0640865.png)
Theoretical closing balance should be the same and I don't think it includes the money from paid orders/invoices, does it?

**Comment by ilmir-k** [comment]
@janbec 

> Theoretical closing balance should be the same and I don't think it includes the money from paid orders/invoices, does it?

It doesn't include the money from paid orders/invoices, i.e. it's taken from built-in **Theoretical Closing Balance** for session:
**Theoretical Closing Balance = Opening Balance + Transactions**

![tcb](https://user-images.githubusercontent.com/14342645/42358597-d3cb310a-80f6-11e8-9ccb-712e3c3101ee.png)

**Comment by janbec** [comment]
## Number of Payments
![image](https://user-images.githubusercontent.com/28890800/42942547-89c1f174-8b60-11e8-8c4a-53f74c1cc6e5.png)
I think the number includes change payments, can we filter them out?

## Opening Balance
![image](https://user-images.githubusercontent.com/28890800/42942685-ff75385e-8b60-11e8-98dd-3ef79c385e25.png)
I'm pretty sure I started with 1,2,5,10,20,50 bill values. I suspect the report only creates rows for bill values available in closing control

## Paid Orders/invoices segment
Prints paid orders/invoices that have been processed outside of date range.

## Theoretical Closing balance
![image](https://user-images.githubusercontent.com/28890800/42943694-c5fd4834-8b63-11e8-8346-701495b4c5e1.png)
Cannot compute this number with numbers printed on report. Attached report to this post.
[Sale_details1.pdf](https://github.com/it-projects-llc/addons-dev/files/2209994/Sale_details1.pdf)
[Sales Details (3).pdf](https://github.com/it-projects-llc/addons-dev/files/2209995/Sales.Details.3.pdf)

## User setting opening and closing balance
Can we display the create_uid of the users doing that somewhere? Preferably at the end...

**Comment by ilmir-k** [comment]
Hi Jan,

We made updates which should fix:
* Opening Balance
* Paid Orders/invoices segment
* Theoretical Closing balance
and you can check it on runbot

But we have the questions:

> 1. Number of Payments

We can filter them out together with returns only, because both change and return are the negative payments

> 2. User setting opening and closing balance

It's not clear where we should place the user id who made opening and closing balance: at the end of table or at the end of row? Note that opening/closing balance could be made by different users for the same session.

**Comment by janbec** [comment]
@ilmir-k Sorry for getting back so late, had a few busy days.

## number of payments
ok, got it, Then also filter the returns as we have them in a seperate view. 

## user of opening and closing balance
If we have the information on who openend AND closed the session in two different fields I would like to print both at the very end after the sums/balances/difference

**Comment by ilmir-k** [comment]
@janbec 

We made work regarding your notes. Please check the latest updates: 
http://runbot.it-projects.info/runbot/33/547
login and pass: admin

**Comment by janbec** [comment]
Hi @ilmir-k

looks good, two issues remaining:

## expenses remain empty
consequently not considered for cash computation.
![image](https://user-images.githubusercontent.com/28890800/44394938-bf3d0900-a538-11e8-84c6-484b41bc7971.png)
![image](https://user-images.githubusercontent.com/28890800/44394955-c6fcad80-a538-11e8-96b7-e38dff713e0b.png)

 ## cash control -> Starting value not computed
![image](https://user-images.githubusercontent.com/28890800/44395025-f4495b80-a538-11e8-8d59-2fb4f72e9e6d.png)

**Comment by ilmir-k** [comment]
@janbec 
Sorry for the issues remaining. We fixed them so you can check it again:
http://runbot.it-projects.info/runbot/33/549
login and pass: admin

**Comment by janbec** [comment]
@ilmir-k 
[Sales Details put money in not considered.pdf](https://github.com/it-projects-llc/addons-dev/files/2314187/Sales.Details.put.money.in.not.considered.pdf)

Issues fixed but I noticed that put money in value is probabaly not considered when computing theoretical closing

See report, computes 5004,75 but should be 5009,75, can you please check?

**Comment by ilmir-k** [comment]
@janbec 

Actually, it is considered. Theoretical closing balance 
3.692 + 3317.75 - 2000 - **5** = 5.004.75

Please check it again and let me know if I missed something

**Comment by janbec** [comment]
@ilmir-k 
We have 697 cash with an opening balance of 3000 but the closing balance has 3692, so I assume that -5 from put money in/take money out is deducted twice?

**Comment by ilmir-k** [comment]
@janbec 

1. we have 3000+697=3697 eur in cashbox 
2. then put 5 eur in, so it is 3702 eur
3. then take 10 eur out, so it is 3692 eur
4. so we need 3692 to close

 Please clarify how it should be in your case?

**Comment by janbec** [comment]
Hi @ilmir-k 
you're right. I was looking at it differently. I made a table regarding the computation.

The first theoretical closing balance: I am not sure why normal card sales are not considered but invoices paid with card. I think we should use that to sum everything up like in column ALL

The cash closing balance for cash should be like table Cash only. So that we have a value that we can count the actual cash against.

Sorry for the confusion.



  | ALL | Current Theoretical 1 | Cash only
-- | -- | -- | --
starting balance | 3.000,00 € | 3.000,00 € | 3.000,00 €
Regular sale card | 1.149,99 € |   |  
Regular Sale | 697,00 € | 697,00 € | 697,00 €
Expenses | -  2.000,00 € | -                                2.000,00 € | -  2.000,00 €
Put in | 5,00 € |   | 5,00 €
Take out | -        10,00 € | -                                    10,00 € | -        10,00 €
Invoice paid | 2.300,00 € | 2.300,00 € | 2.300,00 €
Invoice paid card | 1.017,75 € | 1.017,75 € |  
  | 6.159,74 € | 5.004,75 € | 3.992,00 €

**Comment by ilmir-k** [comment]
Hi @janbec 

So should we change something regarding your computation?
Would you like to change **Theoretical 1** and **Real Closing Balance** like following:

**Theoretical 1 = Starting balance + Regular sale card + Regular Sale + Expenses + Put in + Take out + Invoice paid + Invoice paid card**

**Real Closing Balance = Starting balance + Regular Sale + Expenses + Put in + Take out + Invoice paid**

**Comment by janbec** [comment]
Hi @ilmir-k ,
let's name the field for better understanding:
![image](https://user-images.githubusercontent.com/28890800/45915005-9799d300-be4d-11e8-92a8-ef7573e4903c.png)

> Theoretical 1 = Starting balance + Regular sale card + Regular Sale + Expenses + Put in + Take out + Invoice paid + Invoice paid card
is correct

Real closing balance: computes the money counted from cashbox

Theoretical cash balance: starting balance + regular sale (cash) + expenses + put in + take out + invoices paid cash

**Comment by janbec** [comment]
@ilmir-k 
The real closing balance is the actual cash some counted manually and then entered into odoo. The real closing balance is then computed from the user input.

If the real closing balance does not match the theoretical cash balance, the report should say so and compute the difference. We then have a problem which we need to look into.

In other words:
Real Closing Balance is the actual money we have in the cashbox at the end of the session
Theoretical Cash Balance is the money odoo says we should have in the cashbox.
Ideally, there should be no difference but if there is we need to investigate.

**Comment by ilmir-k** [comment]
@janbec Yes, I completely understand what are the Theoretical Cash Balance and Real Closing Balance for, but after the latest updates **Theoretical Cash Balance** in report and **Theoretical Cash Balance** in pos.session.form are different.

**Theoretical Cash Balance** in pos.session.form is computed as usual by default (without invoices,expenses).
**Theoretical Cash Balance** in report is computed by new method we implemented above by considering paid cash invoices and expenses.

So to avoid the difference I think we should display new **Theoretical Cash Balance** on pos.session.form too instead of old one.
Please confirm if you understand it and can we make such changes.

**Comment by janbec** [comment]
@ilmir-k 
Ah okay, I only thought about the report. If you can easily change the pos.session form view to do what you described, that would be great.
Good thinking :) !

**Comment by ilmir-k** [comment]
@janbec 
Actually, it is not so easy to make such changes but we could try to do it.
We want to warn that due to the newest requirements we have to add extra amount to initial cost for the report development. I hope you understand it :)

**Comment by ilmir-k** [comment]
@janbec 
Please test the latest updates:
http://runbot.it-projects.info/runbot/33/549
login and pass: admin

**Comment by janbec** [comment]
@ilmir-k 
Not sure what was done exactly but I believe the field in difference in payment method table was not changed?
because it seems like the form view computes with invoices and expenses and the payment table only uses put money in and out.
![image](https://user-images.githubusercontent.com/28890800/46275979-06b6ac00-c55f-11e8-8a51-a97636d5012d.png)

**Comment by ilmir-k** [comment]
@janbec 
Yes, I see. We analyzed this moment too and found that it is very difficult and not obviously how to combine 2 models pos.session and account.bank.statement to achieve your requirement above. So we propose to return back the pos.session form as it was by default without taking into account the invoices and expenses.
Waiting for your reply

**Comment by ilmir-k** [comment]
@janbec 

> Missed you at odoo xp ;)

Yes, we didn't fly to OXP this year because have a lot of work to be done but we watched it by youtube channel :) As we see, they have made interesting updates, especially it is IoT 
I hope we will try to be there next year ;)

**Comment by janbec** [comment]
@ilmir-k 
Well, I now see why you wanted to include it in the session form.
Without it, I won't get the counting of the cash right except if I allow a big cash difference on the journal.
And I'am not entirely sure of the accounting implications.

Do we have the necesarry information to line the invoices and expenses paid in a session to that specific session? Maybe we could then have smart buttons providing sums for expenses and invoices paid.
This would at least give some hint on "normal cash"...

**Comment by janbec** [comment]
@ilmir-k 
Or we cut the `real cash balance` and `difference` computation from the report. Instead just have blanks for the user to fill and compute himself.

**Comment by ilmir-k** [comment]
@janbec 
I think we can make both _**add smart button providing sums for expenses and invoices paid**_ and _**cut ``real cash balance`` and ``difference`` computation from the report**_ because the options don't contradict each other as I see.

One moment to be clarified regarding the latest note:
Do I understand correctly? Would you like the users to fill the ``real cash balance`` and ``difference`` manually on printed report using a pen or the users should be able to fill those fields when report generating, e.g. on the wizard?
I need more info about this.

**Comment by janbec** [comment]
@ilmir-k 

> Do I understand correctly? Would you like the users to fill the real cash balance and difference manually on printed report using a pen or the users should be able to fill those fields when report generating, e.g. on the wizard?

Yes, the user will compute manually and fill it out with a pen. seems like the easiest way to get this done and is something that we do now anyway.

**Comment by ilmir-k** [comment]
@janbec 
Ok, I've got it

**Comment by ilmir-k** [comment]
@janbec 

We've done. Please check the latest updates
http://runbot.it-projects.info/runbot/33/549
login: admin
pass: admin

**Comment by ilmir-k** [comment]
@janbec 

Yes. This is because in the report the amount is specified in Euro, but in the session form it is converted to dollars.

**Comment by ilmir-k** [comment]
@janbec 
Great :)
